---
- hosts: switche
  gather_facts: no
  vars:
	  ansible_python_interpreter: python
    ansible_user: admin
    ansible_password: admin
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_connection: network_cli
    ansible_network_provider: ansible-network.cisco_ios
  tasks:
  - name: BACKUP RUNNING CONFIG
    ios_config:
      backup: yes
